services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    environment:
      MY_TIME_ZONE: Europe/Budapest
    network_mode: host

  mosquitto:
    depends_on:
      - homeassistant
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: host

  esphome:
    #image: esphome/esphome:beta
    #image: esphome/esphome:dev
    # image: esphome/esphome:latest
    image: ghcr.io/esphome/esphome:stable
    platform: linux/amd64
    # image: esphome/esphome:2023.5.5
#    devices:
      #  - "/dev/ttyUSB0:/dev/ttyUSB0"
#      - "/dev/bus/usb:/dev/bus/usb"
    # - "/dev/ttyS3:/dev/ttyUSB0"
    privileged: true
    container_name: esphome
    volumes:
      - ./esphome/config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # network_mode: host
    environment:
      - com.centurylinklabs.watchtower.enable=1
      - ESPHOME_DASHBOARD_USE_PING=true
#    ports:
 #     - 6152:6052
  #    - 6123:6123
    restart: unless-stopped
    network_mode: host
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe
