services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strongRootPassword12345
      MYSQL_DATABASE: homeassistant
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: SoStrongMyyPw321
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb:/var/lib/mysql
    network_mode: host

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    environment:
      MY_TIME_ZONE: Europe/Budapest
    network_mode: host

  mosquitto:
    depends_on:
      - homeassistant
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: host
