allow_anonymous false
listener 8883
certfile /mosquitto/config/tls/server.crt
keyfile /mosquitto/config/tls/server.key
tls_version tlsv1.2
persistence true
password_file /mosquitto/config/pwfile
acl_file /mosquitto/config/acl
persistence_file mosquitto.db
persistence_location /mosquitto/data/
log_dest stdout
